---
domain: staging.katuma.org
host_id: es-staging
rails_env: staging
admin_email: info@katuma.org

mail_domain: katuma.org

users_sysadmin:
  - "{{ core_devs }}"
  - dani
  - filipe
  - andy

beta_testers:
  - filipefurtado+espargo@gmail.com
