---

- name: provision redis-{{ redis_instance.name }} service
  template:
    src: "redis.service.j2"
    dest: "/etc/systemd/system/redis-{{ redis_instance.name }}.service"
    mode: "0644"
  become: yes
  register: redis_service_file

- name: provision redis-{{ redis_instance.name }} config
  template:
    src: "redis.conf.j2"
    dest: /etc/redis/redis-{{ redis_instance.name }}.conf
    owner: redis
    group: redis
  become: yes
  register: redis_config_file

- name: create lib directory for redis-{{ redis_instance.name }}
  file:
    path: "/var/lib/redis-{{ redis_instance.name }}"
    state: directory
    owner: redis
    group: redis
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when: redis_service_file.changed

- name: enable redis-{{ redis_instance.name }}
  service:
    name: "redis-{{ redis_instance.name }}"
    state: started
    enabled: yes
  become: yes
  become_user: root

- name: restart redis-{{ redis_instance.name }}
  service:
    name: "redis-{{ redis_instance.name }}"
    state: restarted
  become: yes
  become_user: root
  when: redis_service_file.changed or redis_config_file.changed
