---

# Setup an unprivileged user - needs to be run as root.
- name: create unprivileged user
  user:
    name: "{{ unicorn_user }}"
    state: present
    append: yes
    shell: /bin/bash
  become: yes

- name: add ssh key
  authorized_key:
    user: "{{ unicorn_user }}"
    key: "{{ lookup('file', inventory_dir + '/../files/keys/' + item + '.pub') }}"
    state: present
  with_flattened: "{{ users_sysadmin }}"
  become: yes
  when: ssh_key_path is undefined

# Add ssh key path to run playbook command with --extra-vars
# ex.: --extra-vars "ssh_key_path=.ssh/id_rsa.pub"
- name: add ssh key alternative
  authorized_key:
    user: "{{ unicorn_user }}"
    key: "{{ lookup('file', lookup('env','HOME') + ssh_key_path) }}"
    state: present
  become: yes
  when: ssh_key_path is defined

- name: Write OFN environment variables defaults
  become: true
  template:
    src: defaults.j2
    dest: /etc/default/openfoodnetwork
    group: "{{ unicorn_user }}"
    mode: 0640

- name: Write bash_profile for unicorn user
  become: true
  template:
    src: bash_profile.j2
    dest: "/home/{{ unicorn_user }}/.bash_profile"
    owner: "{{ unicorn_user }}"
    group: "{{ unicorn_user }}"
    mode: 0644

- name: Create sudoers configuration for unicorn user
  become: true
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ unicorn_user }}"
    mode: 0440
