---

# Build codebase

- name: build codebase from git branch
  git:
    repo: "{{ git_repo }}"
    dest: "{{ build_path }}"
    version: "{{ git_version }}"
    refspec: "+refs/pull/*/merge:refs/remotes/origin/pull-request-*"
    force: yes
  tags: clone

- name: symlink custom assets into the build
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ app_user }}"
    state: link
    force: yes
  with_items:
    - { src: "{{ system_path }}", dest: "{{ build_path }}/public/system" }
    - { src: "{{ images_path }}", dest: "{{ build_path }}/public/images" }
    - { src: "{{ files_path }}", dest: "{{ build_path }}/public/files" }
    - { src: "{{ storage_path }}", dest: "{{ build_path }}/storage" }
    - { src: "{{ spree_path }}", dest: "{{ build_path }}/public/spree" }
    - { src: "{{ config_path }}/database.yml", dest: "{{ build_path }}/config/database.yml" }
    - { src: "{{ config_path }}/.env.{{ rails_env }}", dest: "{{ build_path }}/.env.{{ rails_env }}" }
    - { src: "{{ l10n_path }}/states.yml", dest: "{{ build_path }}/db/default/spree/states.yml" }
  tags: symlink

# Ensure the correct Ruby version is activated for this build

- name: Install required Ruby version if needed
  command: bash -lc "./script/rbenv-install.sh"
  args:
    chdir: "{{ build_path }}"
  environment:
    RUBY_CONFIGURE_OPTS: "--with-jemalloc"
  register: rbenv_install
  changed_when: rbenv_install.stdout.find("Installing ruby") != -1

# Install bundler and gems

- name: install bundler
  # This needs to be run inside a bash shell to initialise rbenv
  # See http://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible
  command: bash -lc "./script/install-bundler"
  args:
    chdir: "{{ build_path }}"
  register: bundler
  changed_when: bundler.stdout | length > 0

- name: configure bundler
  command: >
    bash -lc "
      bundle config set --local path '{{ gem_path }}'
      bundle config set --local deployment 'true'
      bundle config set --local without 'development:test'
    "
  args:
    chdir: "{{ build_path }}"
    creates: "{{ build_path }}/.bundle/config"
  become: true
  become_user: "{{ app_user }}"

- name: bundle install app dependencies
  # Note: the 'LANG=...' is a fix for broken rubygems utf8 handling.
  command: >
    bash -lc "bundle install"
  args:
    chdir: "{{ build_path }}"
  environment:
    LANG: "{{ language }}"
    LC_ALL: "{{ language }}"
    LC_COLLATE: "{{ language }}"
  tags:
    - bundle_app
    - skip_ansible_lint
  notify: restart puma

# Ensure the correct Node version is activated

- name: register node version in new build
  slurp:
    src: "{{ build_path }}/.node-version"
  register: deploy_node_version
  become: yes

- name: install node version (and yarn)
  include_role:
    name: nodenv_install
  vars:
    node_version: "{{ deploy_node_version['content'] | b64decode | trim }}"

# Install JS dependencies with yarn

- name: run yarn install
  yarn:
    path: "{{ build_path }}"
    executable: "{{ nodenv_root }}/shims/yarn"
  become: true
  become_user: "{{ app_user }}"

# Update the database

- name: check database status
  command: psql -h {{ db_host }} -U {{ db_user }} -d {{ db }} -c "SELECT true FROM pg_tables WHERE tablename = 'order_cycles';"
  register: table_exists
  ignore_errors: yes
  changed_when: False
  tags: rake

- name: prepare database for the first time
  command: bash -lc "bundle exec rails db:setup RAILS_ENV={{ rails_env }} I_AM_SURE=1"
  args:
    chdir: "{{ build_path }}"
  when: table_exists.stdout.find('0 rows') != -1
  tags:
    - rake
    - skip_ansible_lint

- name: clear transient data
  command: bash -lc "bundle exec rake ofn:data:remove_transient_data RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  tags:
    - rake
    - skip_ansible_lint

- name: precompile assets # noqa 301
  command: bash -lc "bundle exec rake assets:precompile RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  become: yes
  become_user: "{{ app_user }}"

- name: migrate database
  command: bash -lc "bundle exec rake db:migrate RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  tags:
    - rake
    - skip_ansible_lint
  notify: restart puma

# Note: this task can be removed after all servers have been provisioned and deployed
- name: delete current path unless it's a symlink
  file:
    dest: "{{ current_path }}"
    state: absent
  when: current_path_stats.stat.islnk is defined and not current_path_stats.stat.islnk
  notify: restart puma

# Move new build into place

- name: symlink build to current
  file:
    src: "{{ build_path }}"
    dest: "{{ current_path }}"
    owner: "{{ app_user }}"
    state: link
    force: yes
  become: yes
  notify:
    - restart puma
    - restart sidekiq
    - update whenever
