---
domain: openfoodnetwork.de
host_id: de-prod
rails_env: production
admin_email: admin@openfoodfoundation.org

mail_domain: openfoodnetwork.de

certbot_domains:
  - openfoodnetwork.de
  - www.openfoodnetwork.de

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 2G

# Enable external database access for third party integrations
#postgres_listen_addresses:
#  - '*'
#
#custom_hba_entries:
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

unicorn_workers: 2
unicorn_timeout: 360
