---
sudo: required
dist: xenial
cache: bundler
language: python
python: 3.7.1
services:
  - postgresql
addons:
  postgresql: "9.5"

env:
  - task: LINT
  - task: BUILD

before_install:
  - |
    if [ "${task}" == "BUILD" ]; then
      # Remove extra postgres versions from travis
      sudo systemctl postgresql stop
      sudo apt remove --purge postgresql-9.4* postgresql-9.6* postgresql-10*
      sudo rm -f /etc/apt/sources.list.d/pgdg.list
      # Remove RVM from travis
      rvm implode --force
      sudo rm -rf $HOME/.rvm $HOME/.rvmrc /etc/rvmrc /etc/profile.d/rvm.sh /usr/local/rvm /usr/local/bin/rvm
      sed '/rvm/d' /home/travis/.bashrc
      sed '/rvm/d' /home/travis/.bash_profile
      sed '/rvm/d' /home/travis/.profile
      gem uninstall rvm
      unset GEM_HOME
      unset GEM_PATH
      unset RUBY_VERSION
      unset MY_RUBY_HOME
      unset IRBRC
    fi

install:
  - pip install -r requirements.txt

script:
  - bin/setup
  - |
    if [ "${task}" == "LINT" ]; then
      ansible-lint playbooks/*.yml --exclude community
    fi
  - |
    if [ "${task}" == "BUILD" ]; then
      ansible-playbook tests/suite.yml --limit travis --connection local
    fi
