---

nginx_brotli_version: v0.1.2
nginx_modules_path: /etc/nginx/modules
nginx_src_path: /usr/local/src/nginx
nginx_brotli_src_path: /usr/local/src/ngx_brotli
nginx_brotli_build_deps:
  - nginx
  - brotli
  - dpkg-dev
  - build-essential
  - git
  - libpcre3
  - libpcre3-dev
  - zlib1g
  - zlib1g-dev
  - openssl
  - libssl-dev
