---
nodenv_plugins:
  # Allow installation of node versions
  - name: "node-build"
    repo: "https://github.com/nodenv/node-build.git"
    version: main
  # Automatically install yarn after installing node
  - name: "nodenv-yarn-install"
    repo: "https://github.com/pine/nodenv-yarn-install"
    version: master
  # Automatically rehash after installing node
  - name: "nodenv-package-rehash"
    repo: "https://github.com/nodenv/nodenv-package-rehash.git"
    version: master
