---

domain: openfoodnetwork.in
host_id: in-prod
rails_env: production

mail_domain: openfoodnetwork.in

admin_email: info@openfoodnetwork.in

certbot_domains:
  - openfoodnetwork.in
  - www.openfoodnetwork.in

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 1G
