---

domain: openfoodnetwork.net
host_id: us-prod
rails_env: production

admin_email: ofn-usa@openfoodnetwork.net

mail_domain: openfoodnetwork.net

certbot_domains:
  - openfoodnetwork.net
  - www.openfoodnetwork.net

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
swapfile_size: 1G

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
  - "{{ custom_hba_zapier_1 }}"
  - "{{ custom_hba_zapier_2 }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_rails_apm: "false"

# Allow more time to clone big order cycles.
puma_timeout: "120"
