---

# Setup an unprivileged user - needs to be run as root.
- name: create unprivileged user
  user:
    name: "{{ app_user }}"
    state: present
    append: yes
    shell: /bin/bash
  become: yes

- name: Open home directory for reading by nginx
  file:
    path: "{{ app_user_home_path }}"
    mode: "o+x" # Add execute to directory for other users.
  become: yes

- name: add ssh key
  authorized_key:
    user: "{{ app_user }}"
    key: "{{ lookup('file', inventory_dir + '/../files/keys/' + item + '.pub') }}"
    state: present
  with_flattened: "{{ users_sysadmin }}"
  become: yes
  when: ssh_key_path is undefined

# Add ssh key path to run playbook command with --extra-vars
# ex.: --extra-vars "ssh_key_path=~/.ssh/id_rsa.pub"
- name: add ssh key alternative
  authorized_key:
    user: "{{ app_user }}"
    key: "{{ lookup('file', ssh_key_path) }}"
    state: present
  become: yes
  when: ssh_key_path is defined

- name: remove old ssh keys from app user
  authorized_key:
    user: "{{ app_user }}"
    key: "{{ lookup('file', inventory_dir + '/../files/keys/' + item + '.pub') }}"
    state: absent
  with_flattened: "{{ retired_core_devs }}"

- name: Write OFN environment variables defaults
  become: true
  template:
    src: defaults.j2
    dest: "/etc/default/{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0640

# Temporary tasks to migrate to new managed block (see next)
- name: ensure file exist
  become: true
  become_user: "{{ app_user }}"
  file:
    path: "~/.bash_profile"
    state: touch
- name: Remove known un-managed bash_profile content
  become: true
  become_user: "{{ app_user }}"
  replace:
    path: "~/.bash_profile"
    regexp: |
      {{ template_notice | regex_escape() }}

      {{ lookup('template', 'templates/bash_profile.j2') | regex_escape() }}

- name: Load OFN environment vars for user
  become: true
  become_user: "{{ app_user }}"
  blockinfile:
    create: true
    dest: "~/.bash_profile"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: app_user"
    block: |
      {{ lookup('template', 'templates/bash_profile.j2') }}

- name: Create sudoers configuration for app user
  become: true
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ app_user }}"
    mode: 0440
