---

domain: example.com
host_id: es-prod # country initials (eg uk, es, de) and environment (default is prod)
rails_env: production

admin_email: admin@example.com

mail_domain: example.com

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
#
#certbot_domains:
#  - example.com
#  - www.example.com
#  - info.example.com

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
#swapfile_size: 1G

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"

#custom_env_vars: |
#  OFN_FEATURE_CONNECT_AND_LEARN="true"

# Overridable Image Settings
# attachment_url:
# attachment_path:
