---

domain: www.openfoodnetwork.org.uk
host_id: uk-prod
rails_env: production

unicorn_workers: 5
unicorn_timeout: 720

certbot_domains:
  - www.openfoodnetwork.org.uk
  - openfoodnetwork.org.uk

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_nginx_logging: true
enable_rails_apm: "true" # has to be explicitly defined as a string due to some datadog bug
