---

domain: www.openfoodnetwork.org.uk
host_id: uk-prod
rails_env: production

unicorn_workers: 4
unicorn_timeout: 120

swapfile_size: 1G

certbot_domains:
  - www.openfoodnetwork.org.uk
  - openfoodnetwork.org.uk

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_nginx_logging: true
