---

domain: openfoodnetwork.ca
host_id: ca-prod
rails_env: production

admin_email: admin@openfoodnetwork.ca
mail_domain: openfoodnetwork.ca

swapfile_size: 2G
unicorn_timeout: 360

certbot_domains:
  - openfoodnetwork.ca
  - www.openfoodnetwork.ca

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }
