---

domain: openfoodnetwork.org.uk
host_id: uk-prod
rails_env: production

puma_timeout: 120

certbot_domains:
  - openfoodnetwork.org.uk
  - www.openfoodnetwork.org.uk

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_metabase_IPv6 }}"
  - "{{ custom_hba_n8n }}"
  - "{{ custom_hba_n8n_IPv6 }}"
  - "{{ custom_hba_zapier_1 }}"
  - "{{ custom_hba_zapier_2 }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

attachment_url: ofn-uk-production.s3.us-east-1.amazonaws.com

rack_timeout_term_on_timeout: 3
