---

domain: openfoodnetwork.org.uk
host_id: uk-prod
rails_env: production

unicorn_timeout: 720

certbot_domains:
  - openfoodnetwork.org.uk
  - www.openfoodnetwork.org.uk

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - "{{ custom_hba_metabase }}"
  - "{{ custom_hba_n8n }}"
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_nginx_logging: true
enable_rails_apm: "false" # has to be explicitly defined as a string due to some datadog bug

attachment_url: ofn-uk-production.s3.us-east-1.amazonaws.com
