---
- name: ruby_update
  hosts: ofn_servers
  remote_user: "{{ user }}"

  vars_files:
    - vars/default_vars.yml
    - vars.yml

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
      become: yes

  roles:
    - role: zzet.rbenv # Install ruby. If missing run: ansible-galaxy install zzet.rbenv
      become: yes
      rbenv:
        env: user
        version: v0.4.0
        ruby_version: "{{ ruby }}"
      rbenv_users:
        - { name: "{{ unicorn_user }}", home: "{{ unicorn_home_path }}", comment: "Main user"}
      tags: ruby
