---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone:
country_code:
currency:
locale: en                  # Default locale for OFN instance
available_locales: en,es    # Available locales for OFN instance
language: en_US.UTF-8       # Default language for the server
language_packages:          # Language packages for the server
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_au.git
timezone:


# Used for the LetsEncrypt email setting
developer_email: <dev email>

# Users listed here will have their key from /files/keys added to the app_user
users_sysadmin:
  - "{{ core_devs }}"
