---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: America
country_code: CR
currency: CRC
locale: es_CR                  # Default locale for OFN instance
available_locales: es_CR,en    # Available locales for OFN instance
language: es_CR.UTF-8          # Default language for the server
language_packages:             # Language packages for the server
  - language-pack-es-base
l10n_repo: https://github.com/JaquerEspeis/laferia-l10n_cr.git
timezone: America/Costa_Rica


# Used for the LetsEncrypt email setting
developer_email: info@laferia.cr

# Users listed here will have their key from /files/keys added to the app_user
users_sysadmin:
  - rngkll
  - "{{ core_devs }}"
    #  - kmoragas
    #  - valarauco
