---
# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: DE
currency: EUR
locale: de_DE
available_locales: de_DE,en_DE
language: de_DE.UTF-8
language_packages:
  - language-pack-de-base
l10n_repo: https://github.com/coopdevs/l10n_de.git
timezone: Europe/Berlin

# Used for the LetsEncrypt email setting
developer_email: admin@openfoodfoundation.org

users_sysadmin:
  - "{{ core_devs }}"
  - "hendirk"

maintenance_mode_message: >
  Wir fÃ¼hren gerade Wartungsarbeiten durch und sind gleich wieder da.
  Bitte versuchen Sie es in einigen Minuten erneut.
