---
# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: DE
currency: EUR
locale: de_DE
available_locales: de_DE,en_DE
language: de_DE.UTF-8
language_packages:
  - language-pack-de-base
l10n_repo: https://github.com/coopdevs/l10n_de.git
timezone: Europe/Berlin

# Used for the LetsEncrypt email setting
developer_email: admin@openfoodfoundation.org

# Users listed here will have their key from /files/keys added to the unicorn_user
users_sysadmin:
  - "{{ core_devs }}"
