---
# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: ES
currency: EUR
locale: es
available_locales: es,ca,pt,eu,it,fr,en
language: es_ES.UTF-8
language_packages:
  - language-pack-es-base
l10n_repo: https://github.com/openfoodfoundation/l10n_au.git
timezone: Madrid

# Used for the LetsEncrypt email setting
developer_email: info@coopdevs.org

users_sysadmin:
  - "{{ core_devs }}"
  - dani
  - enricostn
  - mikel
  - cesar

maintenance_mode_message: >
  El lloc està en procés de manteniment temporal. Si us plau, torneu-ho a intentar més tard.
