---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: FR
currency: EUR
locale: fr
available_locales: fr,en_FR
language: en_US.UTF-8
language_packages:
  - language-pack-en-base
  - language-pack-fr-base
l10n_repo: https://github.com/openfoodfoundation/l10n_fr.git
timezone: Paris

# Used for the LetsEncrypt email setting
developer_email: admin@coopcircuits.fr

users_sysadmin:
  - "{{ core_devs }}"
  - paco

maintenance_mode_message: >
  Une maintenance est en cours. Merci de patienter, la plateforme sera bientôt à nouveau disponible.
  Veuillez nous excuser pour la gêne occasionnée

puma_workers: 3
puma_threads: 4
