---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone:
country_code: IN
currency: INR
locale:
language:
language_packages:
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_in.git
timezone:

