---

# See https://github.com/openfoodfoundation/ofn-install/wiki/Setup for more info
checkout_zone: Europe
country_code: GB
currency: GBP
locale: en_GB
language: en_GB.UTF-8
language_packages:
  - language-pack-en-base
l10n_repo: https://github.com/openfoodfoundation/l10n_gb.git
timezone: London


developer_email: dev.ofnuk@gmail.com

users_sysadmin:
  - "{{ core_devs }}"
  - lindhop
