---

domain: www.coopcircuits.fr
host_id: fr-prod
rails_env: production

admin_email: admin@coopcircuits.fr

mail_domain: coopcircuits.fr

unicorn_timeout: 240
unicorn_workers: 4

certbot_domains:
  - www.coopcircuits.fr
  - coopcircuits.fr

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_nginx_logging: true
enable_rails_apm: "true" # has to be explicitly defined as a string due to some datadog bug

attachment_path: "home/openfoodnetwork/apps/openfoodnetwork/current/public/spree/products/:id/:style/:basename.:extension"
attachment_url: ofn-prod.s3.us-east-1.amazonaws.com

beta_testers:
  - rachel.arnould@gmail.com
  - coop@au-local.org
  - au-local@outlook.com
  - rachel.arnould+test@protonmail.com
  - rachel.arnould@openfoodfrance.org
  - ingrid.joubert@hotmail.fr
